//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJBookStoreAdmin
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Purchaseds = new HashSet<Purchased>();
            this.ShopCarts = new HashSet<ShopCart>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Author { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        public double Price { get; set; }
        public string Img { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> UploadDate { get; set; }
        public bool OnSell { get; set; }
        public int StockQty { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchased> Purchaseds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCart> ShopCarts { get; set; }
    }
}
